In [1]:
import numpy as np

In [2]:
er = np.array([[1, 0.5, 1.45, 0.75],
               [1.95, 1, 3.1, 1.49],
               [0.67, 0.31, 1, 0.48],
               [1.34, 0.64, 1.98, 1]])

In [3]:
choices = np.asarray([0, 1, 2, 3])
combs = np.array(np.meshgrid(choices, choices, choices, choices)).T.reshape(-1, 4)
print(combs)

[[0 0 0 0]
 [0 1 0 0]
 [0 2 0 0]
 ...
 [3 1 3 3]
 [3 2 3 3]
 [3 3 3 3]]


In [5]:
profits = []

for comb in combs:
    i, j, k, l = comb
    profits.append(er[3, i] * er[i, j] * er[j, k] * er[k, l] * er[l, 3])

In [6]:
max(profits)

1.0436925000000001

In [7]:
combs[profits.index(1.0436925000000001)]

array([0, 1, 2, 0])

In [8]:
profits

[1.0050000000000001,
 0.979875,
 0.9763575000000001,
 1.0100250000000002,
 0.9359999999999999,
 0.9359999999999999,
 0.9969600000000002,
 0.9583680000000001,
 0.99495,
 0.8976824999999999,
 0.99495,
 0.955152,
 1.0050000000000001,
 0.9359999999999999,
 0.99495,
 1.0050000000000001,
 0.979875,
 0.979875,
 0.880907625,
 0.9406800000000002,
 0.9125999999999999,
 0.9359999999999999,
 0.899496,
 0.8925696000000001,
 0.97007625,
 0.8976824999999999,
 0.8976824999999999,
 0.8895743999999998,
 0.979875,
 0.9359999999999999,
 0.8976824999999999,
 0.9359999999999999,
 0.9763575000000001,
 1.0436925000000001,
 0.9763575000000001,
 0.9999247500000003,
 0.909324,
 0.9969600000000002,
 0.9969600000000002,
 0.94878432,
 0.9665939250000001,
 0.95614695,
 0.99495,
 0.94560048,
 0.9763575000000001,
 0.9969600000000002,
 0.99495,
 0.99495,
 1.0100250000000002,
 1.0032915,
 0.9373032,
 1.0100250000000002,
 0.94068,
 0.9583680000000001,
 0.9570816,
 0.9583680000000001,
 0.9999247500000001,
 0.9191348100000